# Generated by Django 3.0.6 on 2020-05-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'allergens',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=2000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ingredient_categories',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_g', models.IntegerField(null=True)),
                ('calories_kcal', models.IntegerField(null=True)),
                ('sugar_g', models.IntegerField(null=True)),
                ('protein_g', models.IntegerField(null=True)),
                ('saturated_fat_g', models.IntegerField(null=True)),
                ('sodium_g', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'nutritions',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'place_of_origins',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('image_url', models.URLField(max_length=2000, null=True)),
                ('description', models.TextField(null=True)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('toasted', models.BooleanField(null=True)),
                ('customization_true', models.BooleanField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category')),
                ('nutrition', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Nutrition')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_ingredient',
            field=models.ManyToManyField(through='product.ProductIngredient', to='product.Ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.SubCategory'),
        ),
        migrations.CreateModel(
            name='IngredientPlaceOfOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Ingredient')),
                ('place_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.PlaceOfOrigin')),
            ],
            options={
                'db_table': 'ingredients_placeoforigins',
            },
        ),
        migrations.CreateModel(
            name='IngredientAllergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Allergen')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Ingredient')),
            ],
            options={
                'db_table': 'ingredients_allergens',
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_allergen',
            field=models.ManyToManyField(through='product.IngredientAllergen', to='product.Allergen'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.IngredientCategory'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_placeoforigin',
            field=models.ManyToManyField(through='product.IngredientPlaceOfOrigin', to='product.PlaceOfOrigin'),
        ),
    ]
