# Generated by Django 3.0.6 on 2020-05-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
