# Generated by Django 3.0.6 on 2020-05-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_ingredient_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customization_true',
            field=models.BooleanField(null=True),
        ),
    ]
